version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zeeks
      POSTGRES_PASSWORD: zeee
      POSTGRES_DB: mynestdb
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network: